### ISSUE TITLE
Publishing to Pypi with Volttron account

### ISSUE THREAD

**Issue by kefeimo** [VOLTTRON/dnp3-python#1]
## Summary
* Extend and repackage on old pydnp3 package, so that Volttron DNP3-driver can use it as a dependency and install from pypi.
* tested with test-pypi: https://test.pypi.org/project/dnp3-python/0.2.0/ 

## Note
* By nature, this is more of a PR that requires review rather than an issue. 
* The assignee(s) is review accordingly.

**Comment by craig8** [comment]
Fixed in #15
