### ISSUE TITLE
Unable to install precompiled 3.10 binary

### ISSUE THREAD

**Issue by Xelus22** [VOLTTRON/dnp3-python#26]
Hi, just have an issue installing the pre-compiled binary 
dnp3_python-0.2.3b3-cp310-cp310-manylinux1_x86_64.whl
on Python 3.10.10. 

says `ERROR: dnp3_python-0.2.3b2-cp310-cp310-manylinux1_x86_64.whl is not a supported wheel on this platform.`

python version: 3.10.10
pip3 version: 23.0.1

EDIT: `pip install dnp3-python` works fine with a WSL install. However on native Windows it does not work and comes back with

```
ERROR: Could not find a version that satisfies the requirement dnp3-python (from versions: none)
ERROR: No matching distribution found for dnp3-python
```

EDIT2: [Solved] Requires Visual Studio and compiling from there to get a windows version.

**Comment by craigpnnl** [comment]
@Xelus22 it looks like you have solved this to make it more general purpose.  Our thoughts were only on linux.  Would you be willing to update the readme to reflect the solution you mention in the issue?
