### ISSUE TITLE
Outstation Database Configuration

### ISSUE THREAD

**Issue by Xelus22** [VOLTTRON/dnp3-python#27]
Just leaving this here as an issue as this new fork (of pydnp3) does not solve the inherent issue of Pybind11 

https://github.com/ChargePoint/pydnp3/issues/11

**Comment by kefeimo** [comment]
@Xelus22, thanks for the feedback, we are planning to implement the outstation database configuration capability API. (Please see  https://github.com/VOLTTRON/dnp3-python/issues/19).
In addition, Could you provide insights on what specific parameters your would like to configure? 
THank you.

**Comment by Xelus22** [comment]
Hello, yep that issue you just made seems exactly it. Just need to  allow the configuration of the database types since currently pybind11 just takes the default and doesn't allow you to change it

**Comment by kefeimo** [comment]
> Hello, yep that issue you just made seems exactly it. Just need to allow the configuration of the database types since currently pybind11 just takes the default and doesn't allow you to change it

@Xelus22 , Thanks for following up the issue. Please follow PR https://github.com/VOLTTRON/dnp3-python/pull/38. And check the example [examples/stack_config_examples.py](https://github.com/VOLTTRON/dnp3-python/pull/38/files#diff-85b528148395c5dda97ba2ed309b31f0abe454a7b43a6501ed08d01adbff04e9)

**Comment by kefeimo** [comment]
addressed with https://github.com/VOLTTRON/dnp3-python/pull/39

**Comment by kefeimo** [comment]
@Xelus22 , issue addressed by PR https://github.com/VOLTTRON/dnp3-python/pull/38., now available at develop branch, and check the example [examples/stack_config_examples.py](https://github.com/VOLTTRON/dnp3-python/pull/38/files#diff-85b528148395c5dda97ba2ed309b31f0abe454a7b43a6501ed08d01adbff04e9)

**Comment by LucaGalvagno** [comment]
I solved the problem modifying src/asiodnp3/DatabaseConfig.h adding a method with a lamba function ("setBinaryConfig") . The pybind11 library has some limitations when it comes to binding templated classes or structs like EventConfig.

Below the changes :

.def_property_readonly(
"binary",
[](const asiodnp3::DatabaseConfig &self) { return &self.binary;},
py::return_value_policy::reference
)
.def("setBinaryConfig",
[](asiodnp3::DatabaseConfig &self, uint16_t index, opendnp3::EventBinaryVariation _evariation,opendnp3::PointClass _clazz ,opendnp3::StaticBinaryVariation _svariation) {
self.binary[index].evariation=_evariation;
self.binary[index].clazz=_clazz;
self.binary[index].svariation=_svariation;
},
py::arg("index"), py::arg("_evariation"), py::arg("_clazz") ,py::arg("_svariation"))
