### ISSUE TITLE
Cannot build for py311

### ISSUE THREAD

**Issue by kefeimo** [VOLTTRON/dnp3-python#33]
Ref:
log: https://github.com/VOLTTRON/dnp3-python/actions/runs/4757291625/jobs/8453926574
```
error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
 1912 |             frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
```

**Comment by craigpnnl** [comment]
@kefeimo I was wondering if you had built it locally with py11

**Comment by kefeimo** [comment]
> 

@craig8, I did. But I forgot it failed last time, that's why I stopped it at py310.

**Comment by Xelus22** [comment]
I've been attempting packaging for 3.11 but haven't had time to truly debug/look into it.
Packaging for windows (with Visual Studio 2022 installed) and the appropriate cmake etc. 
3.10 works fine but 3.11 I run into these issues.
![image](https://user-images.githubusercontent.com/17491233/235404471-d87c357c-1917-4244-ad7e-70e73a533b43.png)

![image](https://user-images.githubusercontent.com/17491233/235403965-b79d86d7-5583-4f54-854c-3ba59e84f41b.png)

**Comment by kefeimo** [comment]
> I've been attempting packaging for 3.11 but haven't had time to truly debug/look into it. Packaging for windows (with Visual Studio 2022 installed) and the appropriate cmake etc. 3.10 works fine but 3.11 I run into these issues. ![image](https://user-images.githubusercontent.com/17491233/235404471-d87c357c-1917-4244-ad7e-70e73a533b43.png)
> 
> ![image](https://user-images.githubusercontent.com/17491233/235403965-b79d86d7-5583-4f54-854c-3ba59e84f41b.png)

@Xelus22 , Thanks for the comment. 
I only build for Linux and haven't tested for Windows yet. Can you describe the process you used to successfully build for Python3.10 on Windows so I can try to reproduce on my end. Especially, 
* Could you confirm the codebase version (for example point to the repo and commit)?
* Could you confirm the dependency versions (e.g., Cmake)
* (This is a wild guess of the root cause, but) Could you go to the /deps/pybind11, then run `git log --oneline` display the output. (In essence, the content should be up-to-date with  https://github.com/pybind/pybind11 [956390a](https://github.com/pybind/pybind11/commit/956390a87f6e2ee6ea20438f3faa05222415018f))

**Comment by Xelus22** [comment]
Yep no worries

- This repo master. 
![image](https://user-images.githubusercontent.com/17491233/235406454-b483f447-d86f-4d25-88ab-4f88e955a1ad.png)


- cmake 3.25.1-msvc1
installed with VS 2022 - 
![image](https://user-images.githubusercontent.com/17491233/235406501-190d58e9-d1f7-4ef6-be88-932d04375fa3.png)

- pybind 11 log
![image](https://user-images.githubusercontent.com/17491233/235406543-01040a7a-0e55-4361-bd08-78f7b7161a75.png)

**Comment by kefeimo** [comment]
> 

Got it. It looks like your pybind11 submodule is behind, which is likely the cause of py3.11 fail (at least for Linux.) We merged PR https://github.com/VOLTTRON/dnp3-python/pull/36 recently to update the submodule pybind11. into develop branch. So, I am hopeful that at you local develop branch, run `git pull --recurse-submodules`, then try to build again and it should succeed. (more on [Git Pull with Submodule](https://openmetric.org/til/programming/git-pull-with-submodule/))

**Comment by Xelus22** [comment]
Yep that worked. Needed to use develop and update the submodules there.
However it is now saying `bdist_wheel` command doesn't exist
![image](https://user-images.githubusercontent.com/17491233/235409215-28c697e9-d1a3-41ab-9ce4-ec5a9683b02a.png)

**Comment by kefeimo** [comment]
@Xelus22 
Can you google "python 3.11 error: invalid command 'bdist_wheel`"? the following links look promising to me
* [Fix Python error: invalid command 'bdist_wheel'](https://sebhastian.com/python-invalid-command-bdistwheel/)
* [Error: invalid command 'bdist_wheel' in Python [Solved]](https://bobbyhadz.com/blog/python-error-invalid-command-bdist-wheel)
* [Why is python setup.py saying invalid command ' ...](https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci)

**Comment by Xelus22** [comment]
Thanks, the first link worked! That created the wheel :)
Looks like it works now
[dnp3_python-0.2.3b3-cp311-cp311-win32.whl.zip](https://github.com/VOLTTRON/dnp3-python/files/11363607/dnp3_python-0.2.3b3-cp311-cp311-win32.whl.zip)

Compiled for win32 py3.11

**Comment by kefeimo** [comment]
@Xelus22 
Out of curiosity, are you using virtual environment on your Windows? How do you accomplish coexistence of python 3.10, 3.11

**Comment by Xelus22** [comment]
Python now comes with its own unified/version control with `py` instead of `python` or `python3` now. you just use `py -V:x.yy` e.g. `py -V:3.10`  or `py -V:3.11` with the commands/files to run after

**Comment by kefeimo** [comment]
> Thanks, the first link worked! That created the wheel :) Looks like it works now [dnp3_python-0.2.3b3-cp311-cp311-win32.whl.zip](https://github.com/VOLTTRON/dnp3-python/files/11363607/dnp3_python-0.2.3b3-cp311-cp311-win32.whl.zip)
> 
> Compiled for win32 py3.11

Good work!!!
On a side note: I provided feedback on PR: [Add Windows Notes-on-Packaging.md](https://github.com/VOLTTRON/dnp3-python/pull/41). It would be awesome to include a solid example on WINDOWS, with commands and output in each step. Especially you have fresh material now.

**Comment by Xelus22** [comment]
And technically this compilation is done on a VM but should in theory work the exact same since I just have a fresh VM for mucking around
